plugins = []
headers = []
redirects = []

[build]
  publish = "."
  publishOrigin = "default"

  [build.environment]
    NETLIFY_FEEDBACK_DRAWER = "false"

  [build.processing]
    [build.processing.css]
    [build.processing.html]
    [build.processing.images]
    [build.processing.js]

  [build.services]

[context.production.environment]
  NETLIFY_FEEDBACK_DRAWER = "false"

[context.deploy-preview.environment]
  NETLIFY_FEEDBACK_DRAWER = "false"

[context.branch-deploy.environment]
  NETLIFY_FEEDBACK_DRAWER = "false"
